export const FETCH_PORTFOLIOS = "FETCH_PORTFOLIOS";
export const SET_FETCHING = "SET_FETCHING";
export const DONE_FETCHING = "DONE_FETCHING";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNUP_ERROR";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
// export const SIGNOUT_ERROR = "SIGNOUT_ERROR";
