// PORTFOLIOS
export const FETCH_PORTFOLIOS = 'FETCH_PORTFOLIOS';
export const FETCHING_PORTFOLIOS_ERROR = 'FETCHING_PORTFOLIOS_ERROR';
export const START_FETCHING_PORTFOLIOS = 'START_FETCHING_PORTFOLIOS';
export const DONE_FETCHING_PORTFOLIOS = 'DONE_FETCHING_PORTFOLIOS';

// SYMBOLS
export const FETCHING_SYMBOLS_ERROR = 'FETCHING_SYMBOLS_ERROR';
export const START_FETCHING_SYMBOLS = 'START_FETCHING_SYMBOLS';
export const DONE_FETCHING_SYMBOLS = 'DONE_FETCHING_SYMBOLS';
export const FETCH_QUOTE = 'FETCH_QUOTE';

// MARKET
export const FETCH_MARKET_NEWS = 'FETCH_MARKET_NEWS';

// AUTHENTICATION
export const START_AUTHENTICATION = 'START_AUTHENTICATION';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
